/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { ObjectType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";

import {
  IsInt,
  Min,
  Max,
  IsOptional,
  IsDate,
  ValidateNested,
  IsEnum,
  IsString,
  MaxLength,
} from "class-validator";

import { Type } from "class-transformer";
import { Doctor } from "../../doctor/base/Doctor";
import { FailurePrediction } from "../../failurePrediction/base/FailurePrediction";
import { EnumPatientGender } from "./EnumPatientGender";
import { Recommendation } from "../../recommendation/base/Recommendation";
import { Report } from "../../report/base/Report";
import { Simulation } from "../../simulation/base/Simulation";

@ObjectType()
class Patient {
  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsInt()
  @Min(-999999999)
  @Max(999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  age!: number | null;

  @ApiProperty({
    required: true,
  })
  @IsDate()
  @Type(() => Date)
  @Field(() => Date)
  createdAt!: Date;

  @ApiProperty({
    required: false,
    type: () => Doctor,
  })
  @ValidateNested()
  @Type(() => Doctor)
  @IsOptional()
  doctor?: Doctor | null;

  @ApiProperty({
    required: false,
    type: () => [FailurePrediction],
  })
  @ValidateNested()
  @Type(() => FailurePrediction)
  @IsOptional()
  failurePredictions?: Array<FailurePrediction>;

  @ApiProperty({
    required: false,
    enum: EnumPatientGender,
  })
  @IsEnum(EnumPatientGender)
  @IsOptional()
  @Field(() => EnumPatientGender, {
    nullable: true,
  })
  gender?: "Option1" | null;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  id!: string;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  name!: string | null;

  @ApiProperty({
    required: false,
    type: () => [Recommendation],
  })
  @ValidateNested()
  @Type(() => Recommendation)
  @IsOptional()
  recommendations?: Array<Recommendation>;

  @ApiProperty({
    required: false,
    type: () => [Report],
  })
  @ValidateNested()
  @Type(() => Report)
  @IsOptional()
  reports?: Array<Report>;

  @ApiProperty({
    required: false,
    type: () => [Simulation],
  })
  @ValidateNested()
  @Type(() => Simulation)
  @IsOptional()
  simulations?: Array<Simulation>;

  @ApiProperty({
    required: true,
  })
  @IsDate()
  @Type(() => Date)
  @Field(() => Date)
  updatedAt!: Date;
}

export { Patient as Patient };
