/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { FailurePredictionListRelationFilter } from "../../failurePrediction/base/FailurePredictionListRelationFilter";
import { ValidateNested, IsOptional } from "class-validator";
import { Type } from "class-transformer";
import { StringFilter } from "../../util/StringFilter";
import { StringNullableFilter } from "../../util/StringNullableFilter";
import { RecommendationListRelationFilter } from "../../recommendation/base/RecommendationListRelationFilter";
import { SimulationListRelationFilter } from "../../simulation/base/SimulationListRelationFilter";

@InputType()
class ImplantWhereInput {
  @ApiProperty({
    required: false,
    type: () => FailurePredictionListRelationFilter,
  })
  @ValidateNested()
  @Type(() => FailurePredictionListRelationFilter)
  @IsOptional()
  @Field(() => FailurePredictionListRelationFilter, {
    nullable: true,
  })
  failurePredictions?: FailurePredictionListRelationFilter;

  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  id?: StringFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  manufacturer?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  name?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: () => RecommendationListRelationFilter,
  })
  @ValidateNested()
  @Type(() => RecommendationListRelationFilter)
  @IsOptional()
  @Field(() => RecommendationListRelationFilter, {
    nullable: true,
  })
  recommendations?: RecommendationListRelationFilter;

  @ApiProperty({
    required: false,
    type: () => SimulationListRelationFilter,
  })
  @ValidateNested()
  @Type(() => SimulationListRelationFilter)
  @IsOptional()
  @Field(() => SimulationListRelationFilter, {
    nullable: true,
  })
  simulations?: SimulationListRelationFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  specifications?: StringNullableFilter;
}

export { ImplantWhereInput as ImplantWhereInput };
