/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { ObjectType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsDate,
  ValidateNested,
  IsOptional,
  IsString,
  MaxLength,
} from "class-validator";
import { Type } from "class-transformer";
import { FailurePrediction } from "../../failurePrediction/base/FailurePrediction";
import { Recommendation } from "../../recommendation/base/Recommendation";
import { Simulation } from "../../simulation/base/Simulation";

@ObjectType()
class Implant {
  @ApiProperty({
    required: true,
  })
  @IsDate()
  @Type(() => Date)
  @Field(() => Date)
  createdAt!: Date;

  @ApiProperty({
    required: false,
    type: () => [FailurePrediction],
  })
  @ValidateNested()
  @Type(() => FailurePrediction)
  @IsOptional()
  failurePredictions?: Array<FailurePrediction>;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  id!: string;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  manufacturer!: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  name!: string | null;

  @ApiProperty({
    required: false,
    type: () => [Recommendation],
  })
  @ValidateNested()
  @Type(() => Recommendation)
  @IsOptional()
  recommendations?: Array<Recommendation>;

  @ApiProperty({
    required: false,
    type: () => [Simulation],
  })
  @ValidateNested()
  @Type(() => Simulation)
  @IsOptional()
  simulations?: Array<Simulation>;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  specifications!: string | null;

  @ApiProperty({
    required: true,
  })
  @IsDate()
  @Type(() => Date)
  @Field(() => Date)
  updatedAt!: Date;
}

export { Implant as Implant };
