/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { FailurePredictionUpdateManyWithoutImplantsInput } from "./FailurePredictionUpdateManyWithoutImplantsInput";
import {
  ValidateNested,
  IsOptional,
  IsString,
  MaxLength,
} from "class-validator";
import { Type } from "class-transformer";
import { RecommendationUpdateManyWithoutImplantsInput } from "./RecommendationUpdateManyWithoutImplantsInput";
import { SimulationUpdateManyWithoutImplantsInput } from "./SimulationUpdateManyWithoutImplantsInput";

@InputType()
class ImplantUpdateInput {
  @ApiProperty({
    required: false,
    type: () => FailurePredictionUpdateManyWithoutImplantsInput,
  })
  @ValidateNested()
  @Type(() => FailurePredictionUpdateManyWithoutImplantsInput)
  @IsOptional()
  @Field(() => FailurePredictionUpdateManyWithoutImplantsInput, {
    nullable: true,
  })
  failurePredictions?: FailurePredictionUpdateManyWithoutImplantsInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  manufacturer?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  name?: string | null;

  @ApiProperty({
    required: false,
    type: () => RecommendationUpdateManyWithoutImplantsInput,
  })
  @ValidateNested()
  @Type(() => RecommendationUpdateManyWithoutImplantsInput)
  @IsOptional()
  @Field(() => RecommendationUpdateManyWithoutImplantsInput, {
    nullable: true,
  })
  recommendations?: RecommendationUpdateManyWithoutImplantsInput;

  @ApiProperty({
    required: false,
    type: () => SimulationUpdateManyWithoutImplantsInput,
  })
  @ValidateNested()
  @Type(() => SimulationUpdateManyWithoutImplantsInput)
  @IsOptional()
  @Field(() => SimulationUpdateManyWithoutImplantsInput, {
    nullable: true,
  })
  simulations?: SimulationUpdateManyWithoutImplantsInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  specifications?: string | null;
}

export { ImplantUpdateInput as ImplantUpdateInput };
