/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { FailurePredictionCreateNestedManyWithoutImplantsInput } from "./FailurePredictionCreateNestedManyWithoutImplantsInput";
import {
  ValidateNested,
  IsOptional,
  IsString,
  MaxLength,
} from "class-validator";
import { Type } from "class-transformer";
import { RecommendationCreateNestedManyWithoutImplantsInput } from "./RecommendationCreateNestedManyWithoutImplantsInput";
import { SimulationCreateNestedManyWithoutImplantsInput } from "./SimulationCreateNestedManyWithoutImplantsInput";

@InputType()
class ImplantCreateInput {
  @ApiProperty({
    required: false,
    type: () => FailurePredictionCreateNestedManyWithoutImplantsInput,
  })
  @ValidateNested()
  @Type(() => FailurePredictionCreateNestedManyWithoutImplantsInput)
  @IsOptional()
  @Field(() => FailurePredictionCreateNestedManyWithoutImplantsInput, {
    nullable: true,
  })
  failurePredictions?: FailurePredictionCreateNestedManyWithoutImplantsInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  manufacturer?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  name?: string | null;

  @ApiProperty({
    required: false,
    type: () => RecommendationCreateNestedManyWithoutImplantsInput,
  })
  @ValidateNested()
  @Type(() => RecommendationCreateNestedManyWithoutImplantsInput)
  @IsOptional()
  @Field(() => RecommendationCreateNestedManyWithoutImplantsInput, {
    nullable: true,
  })
  recommendations?: RecommendationCreateNestedManyWithoutImplantsInput;

  @ApiProperty({
    required: false,
    type: () => SimulationCreateNestedManyWithoutImplantsInput,
  })
  @ValidateNested()
  @Type(() => SimulationCreateNestedManyWithoutImplantsInput)
  @IsOptional()
  @Field(() => SimulationCreateNestedManyWithoutImplantsInput, {
    nullable: true,
  })
  simulations?: SimulationCreateNestedManyWithoutImplantsInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  specifications?: string | null;
}

export { ImplantCreateInput as ImplantCreateInput };
