/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Simulation } from "./Simulation";
import { SimulationCountArgs } from "./SimulationCountArgs";
import { SimulationFindManyArgs } from "./SimulationFindManyArgs";
import { SimulationFindUniqueArgs } from "./SimulationFindUniqueArgs";
import { CreateSimulationArgs } from "./CreateSimulationArgs";
import { UpdateSimulationArgs } from "./UpdateSimulationArgs";
import { DeleteSimulationArgs } from "./DeleteSimulationArgs";
import { Implant } from "../../implant/base/Implant";
import { Patient } from "../../patient/base/Patient";
import { SimulationService } from "../simulation.service";
@graphql.Resolver(() => Simulation)
export class SimulationResolverBase {
  constructor(protected readonly service: SimulationService) {}

  async _simulationsMeta(
    @graphql.Args() args: SimulationCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Simulation])
  async simulations(
    @graphql.Args() args: SimulationFindManyArgs
  ): Promise<Simulation[]> {
    return this.service.simulations(args);
  }

  @graphql.Query(() => Simulation, { nullable: true })
  async simulation(
    @graphql.Args() args: SimulationFindUniqueArgs
  ): Promise<Simulation | null> {
    const result = await this.service.simulation(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Simulation)
  async createSimulation(
    @graphql.Args() args: CreateSimulationArgs
  ): Promise<Simulation> {
    return await this.service.createSimulation({
      ...args,
      data: {
        ...args.data,

        implant: args.data.implant
          ? {
              connect: args.data.implant,
            }
          : undefined,

        patient: args.data.patient
          ? {
              connect: args.data.patient,
            }
          : undefined,
      },
    });
  }

  @graphql.Mutation(() => Simulation)
  async updateSimulation(
    @graphql.Args() args: UpdateSimulationArgs
  ): Promise<Simulation | null> {
    try {
      return await this.service.updateSimulation({
        ...args,
        data: {
          ...args.data,

          implant: args.data.implant
            ? {
                connect: args.data.implant,
              }
            : undefined,

          patient: args.data.patient
            ? {
                connect: args.data.patient,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Simulation)
  async deleteSimulation(
    @graphql.Args() args: DeleteSimulationArgs
  ): Promise<Simulation | null> {
    try {
      return await this.service.deleteSimulation(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => Implant, {
    nullable: true,
    name: "implant",
  })
  async getImplant(
    @graphql.Parent() parent: Simulation
  ): Promise<Implant | null> {
    const result = await this.service.getImplant(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }

  @graphql.ResolveField(() => Patient, {
    nullable: true,
    name: "patient",
  })
  async getPatient(
    @graphql.Parent() parent: Simulation
  ): Promise<Patient | null> {
    const result = await this.service.getPatient(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
